package testfile

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"time"

	file "github.com/dterbah/go-test-gen/utils"
	"github.com/dterbah/gods/list"
	"github.com/dterbah/gods/list/arraylist"
	comparator "github.com/dterbah/gods/utils"
	"github.com/sirupsen/logrus"
)

const TEST_FUNCTION_EXTENSION = "Test"
const IMPORT_CONTENT = `import("testing")`
const FILE_HEADER = "/* Test autogenerated with the tool go-test-gen */"

type FileTest struct {
	path        string
	functions   list.List[string]
	packageName string
}

type FileTestStatus int

const (
	Created FileTestStatus = iota
	Updated
	Error
)

/*
Create new file test case
*/
func NewFileTest(path string) FileTest {
	return FileTest{path: path, functions: arraylist.New(comparator.StringComparator)}
}

/*
Generate the tests for a specific file
*/
func (fileTest FileTest) GenerateTests() FileTestStatus {
	// find functions of the current file
	fileSet := token.NewFileSet()

	node, err := parser.ParseFile(fileSet, fileTest.path, nil, parser.AllErrors)

	if err != nil {
		logrus.Errorf("Error when parsing the file %s", fileTest.path)
		return Error
	}

	fileTest.packageName = node.Name.Name

	for _, decl := range node.Decls {
		if function, isFunction := decl.(*ast.FuncDecl); isFunction {
			functionName := function.Name.Name
			fileTest.functions.Add(functionName)
		}
	}

	return fileTest.writeTests()
}

/*
Write the tests corresponding to the file
*/
func (fileTest FileTest) writeTests() FileTestStatus {
	//testFileName := file.CreateTestFile(fileTest.path)
	testFileContent := fmt.Sprintf("%s\n\n%s\n\n%s\n", getPackageContent(fileTest.packageName), getFileHeader(), IMPORT_CONTENT)
	fileTestPath := file.CreateTestFilePath(fileTest.path)

	// todo: don't override file content

	fileTest.functions.ForEach(func(function string, index int) {
		testFunctionContent := getTestFunctionContent(function)
		testFileContent = fmt.Sprintf("%s\n%s\n", testFileContent, testFunctionContent)
	})

	// write new file content in the file test
	err := os.WriteFile(fileTestPath, []byte(testFileContent), 0644)

	if err != nil {
		return Error
	}

	logrus.Infof("✅ File test %s created !", fileTestPath)
	return Created
}

func getTestFunctionContent(function string) string {
	testFunctionName := fmt.Sprintf("%s%s", function, TEST_FUNCTION_EXTENSION)
	return fmt.Sprintf("func %s(t *testing.T) {\n	// todo implement \n}", testFunctionName)
}

func getPackageContent(packageName string) string {
	return fmt.Sprintf("package %s", packageName)
}

func getFileHeader() string {
	currentTime := time.Now()
	today := currentTime.Format("2006-01-02 15:04:05 Monday")

	return fmt.Sprintf("/* Test autogenerated with the tool go-test-gen. Created %s */", today)
}
