package mathsub

/* Test autogenerated with the tool go-test-gen. Created 2024-06-18 22:45:12 Tuesday */

import (
	"fmt"
	"testing"
)

func SubTest(t *testing.T) {
	// todo implement
	fmt.Print("Test sub")
}
