package main

/* Test autogenerated with the tool go-test-gen. Created 2024-06-26 15:00:17 Wednesday */

import("testing")

func TestAdd(t *testing.T) {
	// todo implement 
}

func TestAddFloat(t *testing.T) {
	// todo implement 
}

func TestPrivateAdd(t *testing.T) {
	// todo implement 
}
