package main

/* Test autogenerated with the tool go-test-gen. Created 2024-06-18 22:45:12 Tuesday */

import (
	"fmt"
	"testing"
)

func AddTest(t *testing.T) {
	// todo implement
	fmt.Print("ok")
}

func AddFloatTest(t *testing.T) {
	// todo implement
}
