package main

/* Test autogenerated with the tool go-test-gen. Created 2024-06-20 00:47:58 Thursday */

import("testing")

func AddTest(t *testing.T) {
	// todo implement 
}

func AddFloatTest(t *testing.T) {
	// todo implement 
}

func privateAddTest(t *testing.T) {
	// todo implement 
}
